# Generated by Django 5.0.1 on 2024-01-08 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('massaraapp', '0002_booking_is_released'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('Studio', 'Studio'), ('Deluxe', 'Deluxe'), ('1BHK', '1BHK'), ('2BHK', '2BHK'), ('3BHK', '3BHK')], max_length=10),
        ),
    ]
