# Generated by Django 5.0.1 on 2024-01-08 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('massaraapp', '0004_alter_room_options_room_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_canceled',
            field=models.BooleanField(default=False),
        ),
    ]
