# Generated by Django 4.2 on 2024-01-18 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('massaraapp', '0005_booking_is_canceled'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
